#!/usr/bin/env python3
"""Agent OS — Compile Context Pack

Generate a task-scoped context pack from workspace state.

Usage:
    python compile_context_pack.py --task "refactor auth" --label "auth-refactor"
    python compile_context_pack.py --task "daily audit" --label "daily-audit"

Reads .agent-os/findings.jsonl and .agent-os/mission-control/ to build a compact
context summary. Writes to .agent-os/context-packs/YYYY-MM-DD-<label>.md.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_AGENT_OS_DIR = ".agent-os"
FINDINGS_FILE = "findings.jsonl"
CONTEXT_PACKS_DIR = "context-packs"
MISSION_CONTROL_DIR = "mission-control"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_agent_os_root(project_root: str | None = None) -> Path:
    start = Path(project_root) if project_root else Path.cwd()
    candidate = start / DEFAULT_AGENT_OS_DIR
    if candidate.is_dir():
        return candidate
    for parent in start.parents:
        candidate = parent / DEFAULT_AGENT_OS_DIR
        if candidate.is_dir():
            return candidate
    return start / DEFAULT_AGENT_OS_DIR


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _read_findings(agent_os_root: Path) -> list[dict[str, Any]]:
    path = agent_os_root / FINDINGS_FILE
    if not path.exists():
        return []
    items: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            try:
                items.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return items


def _read_latest_mission_control(agent_os_root: Path) -> str | None:
    mc_dir = agent_os_root / MISSION_CONTROL_DIR
    if not mc_dir.exists():
        return None
    md_files = sorted(mc_dir.glob("*.md"), reverse=True)
    if not md_files:
        return None
    return md_files[0].read_text(encoding="utf-8")


def _scan_workspace_files(project_root: Path) -> list[str]:
    """Quick scan for key project files that might be relevant."""
    indicators = [
        "README.md", "CHANGELOG.md", "package.json", "pyproject.toml",
        "setup.py", "Cargo.toml", "go.mod", "Makefile",
    ]
    found = []
    for name in indicators:
        if (project_root / name).exists():
            found.append(name)
    return found


# ---------------------------------------------------------------------------
# Core Logic
# ---------------------------------------------------------------------------

def compile_context_pack(
    agent_os_root: Path,
    project_root: Path,
    task: str,
    label: str,
    goal: str = "",
    forbidden: str = "",
    expected_output: str = "",
    must_read: str = "",
) -> str:
    """Build context pack content and return as string."""
    findings = _read_findings(agent_os_root)

    # Filter open P0/P1
    open_blockers = [
        f for f in findings
        if f.get("status") in ("open", "accepted") and f.get("severity") in ("P0", "P1")
    ]

    # Latest mission control summary
    mc_content = _read_latest_mission_control(agent_os_root)
    mc_summary = "No mission control available."
    if mc_content:
        # Extract first 3 non-empty lines as summary
        lines = [l.strip() for l in mc_content.splitlines() if l.strip()][:5]
        mc_summary = "\n".join(lines)

    # Workspace files
    workspace_files = _scan_workspace_files(project_root)

    # Build the pack
    today = _today()
    sections = [
        f"# Context Pack: {label}",
        "",
        f"**Date**: {today}",
        f"**Task**: {task}",
        f"**Generated by**: agent-os compile-context-pack",
        "",
        "## Current Goal",
        "",
        goal if goal else f"Complete task: {task}",
        "",
        "## Must-Read Files",
        "",
    ]

    if must_read:
        for f in must_read.split(","):
            sections.append(f"- `{f.strip()}` — relevant to task")
    else:
        sections.append("- <none specified — agent should scan workspace>")

    sections.append("")
    sections.append("## Open Blockers")
    sections.append("")

    if open_blockers:
        for b in open_blockers:
            bid = b.get("id", "?")
            btitle = b.get("title", "?")
            bsev = b.get("severity", "?")
            sections.append(f"- {bid}: {btitle} [{bsev}]")
    else:
        sections.append("- No open P0/P1 findings")

    sections.append("")
    sections.append("## Active Repos / Worktrees")
    sections.append("")
    sections.append(f"- {project_root.name} — see workspace files: {', '.join(workspace_files) or 'none detected'}")

    sections.append("")
    sections.append("## Forbidden Actions")
    sections.append("")
    if forbidden:
        for f in forbidden.split(","):
            sections.append(f"- {f.strip()}")
    else:
        sections.append("- <none specified>")

    sections.append("")
    sections.append("## Expected Output")
    sections.append("")
    if expected_output:
        sections.append(f"- {expected_output}")
    else:
        sections.append(f"- Complete the task: {task}")

    sections.append("")
    sections.append("## Mission Control Summary")
    sections.append("")
    sections.append(mc_summary)
    sections.append("")

    return "\n".join(sections)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="compile_context_pack",
        description="Generate a context pack from workspace state",
    )
    parser.add_argument("--project-root", default=None,
                        help="Project root directory (default: cwd)")
    parser.add_argument("--task", required=True,
                        help="What this context pack is for (required)")
    parser.add_argument("--label", default=None,
                        help="Label for the filename (default: derived from task)")
    parser.add_argument("--goal", default="",
                        help="Override the current goal section")
    parser.add_argument("--must-read", default="",
                        help="Comma-separated list of must-read file paths")
    parser.add_argument("--forbidden", default="",
                        help="Comma-separated list of forbidden actions")
    parser.add_argument("--expected-output", default="",
                        help="What success looks like")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print pack to stdout without writing")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    project_root = Path(args.project_root) if args.project_root else Path.cwd()
    agent_os_root = _find_agent_os_root(str(project_root))

    label = args.label or args.task.lower().replace(" ", "-")[:40]
    today = _today()
    filename = f"{today}-{label}.md"

    content = compile_context_pack(
        agent_os_root=agent_os_root,
        project_root=project_root,
        task=args.task,
        label=label,
        goal=args.goal,
        forbidden=args.forbidden,
        expected_output=args.expected_output,
        must_read=args.must_read,
    )

    if args.dry_run:
        print(f"[DRY RUN] Would write to: {agent_os_root / CONTEXT_PACKS_DIR / filename}")
        print("---")
        print(content)
        return 0

    # Write
    packs_dir = agent_os_root / CONTEXT_PACKS_DIR
    packs_dir.mkdir(parents=True, exist_ok=True)
    out_path = packs_dir / filename
    out_path.write_text(content, encoding="utf-8")
    print(f"Context pack written to: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
